module "aws" {
  source                = "./modules/aws"
  region                        = var.region
  aws_profile                   = var.aws_profile
  aws_shared_credentials_file   = var.aws_shared_credentials_file
  name                          = var.name
  caseNo                        = var.caseNo
  os_name                       = var.os_name
  os_version                    = var.os_version
  manager_count                 = var.manager_count
  manager_instance_type         = var.manager_instance_type
  msr_count                     = var.msr_count
  msr_instance_type             = var.msr_instance_type
  nfs_backend                   = var.nfs_backend
  worker_count                  = var.worker_count
  worker_instance_type          = var.worker_instance_type
  win_worker_count              = var.win_worker_count
  win_worker_instance_type      = var.win_worker_instance_type
  mcr_version                   = var.mcr_version
  mke_version                   = var.mke_version
  msr_version                   = var.msr_version
  image_repo                    = var.image_repo
  publicKey                     = var.publicKey
}